In [26]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,Normalizer,MinMaxScaler,LabelEncoder,StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.metrics import classification_report
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.tree import DecisionTreeClassifier

In [27]:
df = pd.read_csv("../final_data_to_clean.csv")
df

,PROMISE_STATUS_O,EXTENSION_ELIGIBLE_Y,F0223_NUMBER_OF_EXTENSIONS,lastchannel_Z,REM_TM_RAT_OBS,ApplicantFICOScore,Appl_Debt,F0066_CONTACT_NO_PROMISE_COUNT,F0315_DAYS_SINCE_LAST_PROMISE_1,F0065_PROMISES_TAKEN_COUNT,...,PTI_BOOKED,SalesTax,DOWN_CASH,FINANCED_AMOUNT,DSL_NSF,F0089_PROMISE_AMT_1,DSL_ext,F0180_CURRENT_INTEREST_RATE,BAL_RAT_TRN_6.1,DPD_bool
0,0.0,0.0,3.0,1.0,0.0,0.0,1075.05,12.0,5.0,25.0,...,0.0964,708.22,0.0,15057.22,NaN,382.68,20.0,0.1999,0.01,False
1,0.0,1.0,0.0,1.0,0.0,0.0,1138.75,3.0,45.0,3.0,...,0.1006,0.00,3500.0,20095.17,NaN,419.21,NaN,0.1425,0.03,False
2,0.0,1.0,0.0,1.0,0.0,551.0,767.83,0.0,3.0,3.0,...,0.1525,1916.82,5000.0,18764.82,NaN,432.01,NaN,0.1808,0.03,False
3,1.0,0.0,2.0,1.0,0.0,468.0,1071.20,14.0,-11.0,10.0,...,0.0903,0.00,3000.0,15077.00,43.0,361.22,104.0,0.1970,0.02,False
4,0.0,1.0,0.0,1.0,0.0,523.0,726.64,2.0,80.0,7.0,...,0.1354,880.60,3000.0,10200.54,NaN,280.21,NaN,0.2134,0.05,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
63004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
63005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
63006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
63007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [28]:
df=df[0:62938]
df

,PROMISE_STATUS_O,EXTENSION_ELIGIBLE_Y,F0223_NUMBER_OF_EXTENSIONS,lastchannel_Z,REM_TM_RAT_OBS,ApplicantFICOScore,Appl_Debt,F0066_CONTACT_NO_PROMISE_COUNT,F0315_DAYS_SINCE_LAST_PROMISE_1,F0065_PROMISES_TAKEN_COUNT,...,PTI_BOOKED,SalesTax,DOWN_CASH,FINANCED_AMOUNT,DSL_NSF,F0089_PROMISE_AMT_1,DSL_ext,F0180_CURRENT_INTEREST_RATE,BAL_RAT_TRN_6.1,DPD_bool
0,0.0,0.0,3.0,1.0,0.0,0.0,1075.05,12.0,5.0,25.0,...,0.0964,708.22,0.0,15057.22,NaN,382.68,20.0,0.1999,0.01,False
1,0.0,1.0,0.0,1.0,0.0,0.0,1138.75,3.0,45.0,3.0,...,0.1006,0.00,3500.0,20095.17,NaN,419.21,NaN,0.1425,0.03,False
2,0.0,1.0,0.0,1.0,0.0,551.0,767.83,0.0,3.0,3.0,...,0.1525,1916.82,5000.0,18764.82,NaN,432.01,NaN,0.1808,0.03,False
3,1.0,0.0,2.0,1.0,0.0,468.0,1071.20,14.0,-11.0,10.0,...,0.0903,0.00,3000.0,15077.00,43.0,361.22,104.0,0.1970,0.02,False
4,0.0,1.0,0.0,1.0,0.0,523.0,726.64,2.0,80.0,7.0,...,0.1354,880.60,3000.0,10200.54,NaN,280.21,NaN,0.2134,0.05,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62933,0.0,0.0,2.0,1.0,0.0,496.0,1808.27,4.0,17.0,7.0,...,0.0877,1040.82,2000.0,17252.97,NaN,437.95,20.0,0.1800,0.01,False
62934,1.0,1.0,0.0,1.0,0.0,458.0,720.43,1.0,-16.0,9.0,...,0.1728,841.68,2100.0,15382.68,NaN,402.48,NaN,0.2140,0.03,False
62935,0.0,1.0,1.0,1.0,0.0,567.0,852.94,3.0,502.0,13.0,...,0.1321,872.19,1500.0,15924.07,NaN,371.17,166.0,0.1650,0.04,False
62936,0.0,0.0,4.0,1.0,0.0,447.0,1026.95,11.0,31.0,16.0,...,0.1338,1152.30,4000.0,18715.30,NaN,500.00,170.0,0.2425,0.00,True
62937,0.0,0.0,2.0,1.0,0.0,0.0,860.65,2.0,17.0,1.0,...,0.0931,0.00,800.0,12305.00,NaN,136.03,19.0,0.2399,0.03,False

In [14]:
# We dont have any categrical so one hot is not possible.

In [29]:
(df.isnull().sum()/df.shape[0])*100

PROMISE_STATUS_O                              0.000000
EXTENSION_ELIGIBLE_Y                          0.000000
F0223_NUMBER_OF_EXTENSIONS                    0.000000
lastchannel_Z                                 0.000000
REM_TM_RAT_OBS                                0.000000
ApplicantFICOScore                            0.000000
Appl_Debt                                     0.000000
F0066_CONTACT_NO_PROMISE_COUNT               11.911723
F0315_DAYS_SINCE_LAST_PROMISE_1              11.462074
F0065_PROMISES_TAKEN_COUNT                    6.477804
F0068_ATTEMPTED_CONTACT_COUNT                 8.896056
F0071_CORRESPONDENCE_COUNT                   12.876164
F0305_TODAY_MINUS_CONTACT_NO_PROMISE_DATE    23.782135
F0306_TODAY_MINUS_LEFT_MESSAGES_DATE         47.553148
F0314_TODAY_MINUS_DAYS_LAST_CONTACT           9.347294
F0317_DAYS_SINCE_LAST_LETTER                 30.669866
F0320_TODAY_MINUS_DAYS_LAST_MONETARY          0.000000
F0381_DAYS_DELINQUENT_360                     0.000000
BALANCE_PERCENT_LOAN                          4.590232
F0146_PAST_DUE_PAYMENTS                       4.590232
DSLP                                          2.127491
F0223_NUMBER_OF_EXTENSIONS.1                  0.000000
PMT_RAT_OBS                                   4.590232
PaymentAmtLast60Days                          0.000000
PaymentAmtLast90Days                          0.000000
PaymentNumLast120Days                         0.000000
PmtNumFullAmtLast60Days                       0.000000
D5P_TOT_1                                     0.000000
D31P_TOT_6                                    0.000000
DD_AVG_1                                      0.000000
BAL_RAT_TRN_6                                 0.000000
CBTINDIRECTGEN23                             19.102927
CBTINDIRECTGEN30                             95.729130
LOANFUNDINGSCORE                              0.007944
LTVEffective                                  4.596587
DepreciationRate                              0.007944
Appl_Income                                   0.000000
PTI_BOOKED                                    0.000000
SalesTax                                      0.000000
DOWN_CASH                                     0.000000
FINANCED_AMOUNT                               0.000000
DSL_NSF                                      81.211669
F0089_PROMISE_AMT_1                           6.870253
DSL_ext                                      55.684960
F0180_CURRENT_INTEREST_RATE                   0.000000
BAL_RAT_TRN_6.1                               0.000000
DPD_bool                                      0.000000
dtype: float64

In [30]:
remove_df = df.drop(columns=["F0305_TODAY_MINUS_CONTACT_NO_PROMISE_DATE",
                "F0306_TODAY_MINUS_LEFT_MESSAGES_DATE",
                "F0317_DAYS_SINCE_LAST_LETTER",
                "CBTINDIRECTGEN30",
                "DSL_NSF",
                "DSL_ext"])
remove_df

,PROMISE_STATUS_O,EXTENSION_ELIGIBLE_Y,F0223_NUMBER_OF_EXTENSIONS,lastchannel_Z,REM_TM_RAT_OBS,ApplicantFICOScore,Appl_Debt,F0066_CONTACT_NO_PROMISE_COUNT,F0315_DAYS_SINCE_LAST_PROMISE_1,F0065_PROMISES_TAKEN_COUNT,...,DepreciationRate,Appl_Income,PTI_BOOKED,SalesTax,DOWN_CASH,FINANCED_AMOUNT,F0089_PROMISE_AMT_1,F0180_CURRENT_INTEREST_RATE,BAL_RAT_TRN_6.1,DPD_bool
0,0.0,0.0,3.0,1.0,0.0,0.0,1075.05,12.0,5.0,25.0,...,0.694261,4138.00,0.0964,708.22,0.0,15057.22,382.68,0.1999,0.01,False
1,0.0,1.0,0.0,1.0,0.0,0.0,1138.75,3.0,45.0,3.0,...,0.776757,4166.67,0.1006,0.00,3500.0,20095.17,419.21,0.1425,0.03,False
2,0.0,1.0,0.0,1.0,0.0,551.0,767.83,0.0,3.0,3.0,...,0.834200,2833.33,0.1525,1916.82,5000.0,18764.82,432.01,0.1808,0.03,False
3,1.0,0.0,2.0,1.0,0.0,468.0,1071.20,14.0,-11.0,10.0,...,0.810160,4000.00,0.0903,0.00,3000.0,15077.00,361.22,0.1970,0.02,False
4,0.0,1.0,0.0,1.0,0.0,523.0,726.64,2.0,80.0,7.0,...,0.810160,2069.02,0.1354,880.60,3000.0,10200.54,280.21,0.2134,0.05,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62933,0.0,0.0,2.0,1.0,0.0,496.0,1808.27,4.0,17.0,7.0,...,0.776757,4991.09,0.0877,1040.82,2000.0,17252.97,437.95,0.1800,0.01,False
62934,1.0,1.0,0.0,1.0,0.0,458.0,720.43,1.0,-16.0,9.0,...,0.856943,2218.75,0.1728,841.68,2100.0,15382.68,402.48,0.2140,0.03,False
62935,0.0,1.0,1.0,1.0,0.0,567.0,852.94,3.0,502.0,13.0,...,0.629297,2810.34,0.1321,872.19,1500.0,15924.07,371.17,0.1650,0.04,False
62936,0.0,0.0,4.0,1.0,0.0,447.0,1026.95,11.0,31.0,16.0,...,0.629297,3704.74,0.1338,1152.30,4000.0,18715.30,500.00,0.2425,0.00,True
62937,0.0,0.0,2.0,1.0,0.0,0.0,860.65,2.0,17.0,1.0,...,0.734352,3500.00,0.0931,0.00,800.0,12305.00,136.03,0.2399,0.03,False

In [34]:
print("\n\n No. of different values in each column with datatype")
column_metadata=pd.DataFrame(columns=["Name","#Unique_values","Column_type"])
for i,col in enumerate(remove_df.columns):
    column_metadata.loc[i,"Name"]=col
    column_metadata.loc[i,"#Unique_values"]=remove_df[col].nunique()
    column_metadata.loc[i,"Column_type"]=remove_df[col].dtype
column_metadata

 No. of different values in each column with datatype

                                    Name #Unique_values Column_type
0                       PROMISE_STATUS_O              2     float64
1                   EXTENSION_ELIGIBLE_Y              2     float64
2             F0223_NUMBER_OF_EXTENSIONS              7     float64
3                          lastchannel_Z              2     float64
4                         REM_TM_RAT_OBS              2     float64
5                     ApplicantFICOScore            391     float64
6                              Appl_Debt          51423     float64
7         F0066_CONTACT_NO_PROMISE_COUNT            148     float64
8        F0315_DAYS_SINCE_LAST_PROMISE_1           1512     float64
9             F0065_PROMISES_TAKEN_COUNT            124     float64
10         F0068_ATTEMPTED_CONTACT_COUNT           1553     float64
11            F0071_CORRESPONDENCE_COUNT            239     float64
12   F0314_TODAY_MINUS_DAYS_LAST_CONTACT           1275     float64
13  F0320_TODAY_MINUS_DAYS_LAST_MONETARY            373     float64
14             F0381_DAYS_DELINQUENT_360           1060     float64
15                  BALANCE_PERCENT_LOAN           9159     float64
16               F0146_PAST_DUE_PAYMENTS          20956     float64
17                                  DSLP            372     float64
18          F0223_NUMBER_OF_EXTENSIONS.1              7     float64
19                           PMT_RAT_OBS           7680     float64
20                  PaymentAmtLast60Days          36807     float64
21                  PaymentAmtLast90Days          42656     float64
22                 PaymentNumLast120Days             24     float64
23               PmtNumFullAmtLast60Days             13     float64
24                             D5P_TOT_1             31     float64
25                            D31P_TOT_6            181     float64
26                              DD_AVG_1           1067     float64
27                         BAL_RAT_TRN_6            130     float64
28                      CBTINDIRECTGEN23            485     float64
29                      LOANFUNDINGSCORE            326     float64
30                          LTVEffective          58048     float64
31                      DepreciationRate            659     float64
32                           Appl_Income          32130     float64
33                            PTI_BOOKED          13847     float64
34                              SalesTax          40832     float64
35                             DOWN_CASH           2723     float64
36                       FINANCED_AMOUNT          58030     float64
37                   F0089_PROMISE_AMT_1          30223     float64
38           F0180_CURRENT_INTEREST_RATE            802     float64
39                       BAL_RAT_TRN_6.1            130     float64
40                              DPD_bool              2        bool

### 0-4,18 columns impute with mode.

In [59]:
#

In [58]:
from collections import Counter
remove_df["PROMISE_STATUS_O"].replace(np.nan,Counter(remove_df["PROMISE_STATUS_O"]).most_common()[0][0],inplace=True)
remove_df["PROMISE_STATUS_O"].isnull().sum()

0

In [60]:
remove_df["EXTENSION_ELIGIBLE_Y"].replace(np.nan,Counter(remove_df["EXTENSION_ELIGIBLE_Y"]).most_common()[0][0],inplace=True)
remove_df["lastchannel_Z"].replace(np.nan,Counter(remove_df["lastchannel_Z"]).most_common()[0][0],inplace=True)
remove_df["REM_TM_RAT_OBS"].replace(np.nan,Counter(remove_df["REM_TM_RAT_OBS"]).most_common()[0][0],inplace=True)

remove_df

,PROMISE_STATUS_O,EXTENSION_ELIGIBLE_Y,F0223_NUMBER_OF_EXTENSIONS,lastchannel_Z,REM_TM_RAT_OBS,ApplicantFICOScore,Appl_Debt,F0066_CONTACT_NO_PROMISE_COUNT,F0315_DAYS_SINCE_LAST_PROMISE_1,F0065_PROMISES_TAKEN_COUNT,...,DepreciationRate,Appl_Income,PTI_BOOKED,SalesTax,DOWN_CASH,FINANCED_AMOUNT,F0089_PROMISE_AMT_1,F0180_CURRENT_INTEREST_RATE,BAL_RAT_TRN_6.1,DPD_bool
0,0.0,0.0,3.0,1.0,0.0,0.0,1075.05,12.0,5.0,25.0,...,0.694261,4138.00,0.0964,708.22,0.0,15057.22,382.68,0.1999,0.01,False
1,0.0,1.0,0.0,1.0,0.0,0.0,1138.75,3.0,45.0,3.0,...,0.776757,4166.67,0.1006,0.00,3500.0,20095.17,419.21,0.1425,0.03,False
2,0.0,1.0,0.0,1.0,0.0,551.0,767.83,0.0,3.0,3.0,...,0.834200,2833.33,0.1525,1916.82,5000.0,18764.82,432.01,0.1808,0.03,False
3,1.0,0.0,2.0,1.0,0.0,468.0,1071.20,14.0,-11.0,10.0,...,0.810160,4000.00,0.0903,0.00,3000.0,15077.00,361.22,0.1970,0.02,False
4,0.0,1.0,0.0,1.0,0.0,523.0,726.64,2.0,80.0,7.0,...,0.810160,2069.02,0.1354,880.60,3000.0,10200.54,280.21,0.2134,0.05,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62933,0.0,0.0,2.0,1.0,0.0,496.0,1808.27,4.0,17.0,7.0,...,0.776757,4991.09,0.0877,1040.82,2000.0,17252.97,437.95,0.1800,0.01,False
62934,1.0,1.0,0.0,1.0,0.0,458.0,720.43,1.0,-16.0,9.0,...,0.856943,2218.75,0.1728,841.68,2100.0,15382.68,402.48,0.2140,0.03,False
62935,0.0,1.0,1.0,1.0,0.0,567.0,852.94,3.0,502.0,13.0,...,0.629297,2810.34,0.1321,872.19,1500.0,15924.07,371.17,0.1650,0.04,False
62936,0.0,0.0,4.0,1.0,0.0,447.0,1026.95,11.0,31.0,16.0,...,0.629297,3704.74,0.1338,1152.30,4000.0,18715.30,500.00,0.2425,0.00,True
62937,0.0,0.0,2.0,1.0,0.0,0.0,860.65,2.0,17.0,1.0,...,0.734352,3500.00,0.0931,0.00,800.0,12305.00,136.03,0.2399,0.03,False

In [63]:
#Imputed with median
for col in remove_df.columns:
    remove_df[col].replace(np.nan,remove_df[col].median(),inplace=True)
remove_df.isnull().sum()

PROMISE_STATUS_O                        0
EXTENSION_ELIGIBLE_Y                    0
F0223_NUMBER_OF_EXTENSIONS              0
lastchannel_Z                           0
REM_TM_RAT_OBS                          0
ApplicantFICOScore                      0
Appl_Debt                               0
F0066_CONTACT_NO_PROMISE_COUNT          0
F0315_DAYS_SINCE_LAST_PROMISE_1         0
F0065_PROMISES_TAKEN_COUNT              0
F0068_ATTEMPTED_CONTACT_COUNT           0
F0071_CORRESPONDENCE_COUNT              0
F0314_TODAY_MINUS_DAYS_LAST_CONTACT     0
F0320_TODAY_MINUS_DAYS_LAST_MONETARY    0
F0381_DAYS_DELINQUENT_360               0
BALANCE_PERCENT_LOAN                    0
F0146_PAST_DUE_PAYMENTS                 0
DSLP                                    0
F0223_NUMBER_OF_EXTENSIONS.1            0
PMT_RAT_OBS                             0
PaymentAmtLast60Days                    0
PaymentAmtLast90Days                    0
PaymentNumLast120Days                   0
PmtNumFullAmtLast60Days                 0
D5P_TOT_1                               0
D31P_TOT_6                              0
DD_AVG_1                                0
BAL_RAT_TRN_6                           0
CBTINDIRECTGEN23                        0
LOANFUNDINGSCORE                        0
LTVEffective                            0
DepreciationRate                        0
Appl_Income                             0
PTI_BOOKED                              0
SalesTax                                0
DOWN_CASH                               0
FINANCED_AMOUNT                         0
F0089_PROMISE_AMT_1                     0
F0180_CURRENT_INTEREST_RATE             0
BAL_RAT_TRN_6.1                         0
DPD_bool                                0
dtype: int64

In [41]:
#Outliers

In [46]:
q1=remove_df.quantile(0.25)
q3=remove_df.quantile(0.75)
IQR = q3-q1
IQR

PROMISE_STATUS_O                            0.000000
EXTENSION_ELIGIBLE_Y                        1.000000
F0223_NUMBER_OF_EXTENSIONS                  2.000000
lastchannel_Z                               0.000000
REM_TM_RAT_OBS                              0.000000
ApplicantFICOScore                        554.000000
Appl_Debt                                 652.442500
F0066_CONTACT_NO_PROMISE_COUNT             10.000000
F0315_DAYS_SINCE_LAST_PROMISE_1           132.000000
F0065_PROMISES_TAKEN_COUNT                 20.000000
F0068_ATTEMPTED_CONTACT_COUNT             300.000000
F0071_CORRESPONDENCE_COUNT                 70.000000
F0314_TODAY_MINUS_DAYS_LAST_CONTACT       122.000000
F0320_TODAY_MINUS_DAYS_LAST_MONETARY       20.000000
F0381_DAYS_DELINQUENT_360                  33.000000
BALANCE_PERCENT_LOAN                        0.374900
F0146_PAST_DUE_PAYMENTS                   406.480000
DSLP                                       20.000000
F0223_NUMBER_OF_EXTENSIONS.1                2.000000
PMT_RAT_OBS                                 0.142700
PaymentAmtLast60Days                      492.760000
PaymentAmtLast90Days                      634.325000
PaymentNumLast120Days                       1.000000
PmtNumFullAmtLast60Days                     1.000000
D5P_TOT_1                                  22.000000
D31P_TOT_6                                 14.000000
DD_AVG_1                                   26.000000
BAL_RAT_TRN_6                               0.030000
CBTINDIRECTGEN23                           83.000000
LOANFUNDINGSCORE                           61.000000
LTVEffective                            58796.064516
DepreciationRate                            0.302444
Appl_Income                              2176.005000
PTI_BOOKED                                  0.058200
SalesTax                                  620.077500
DOWN_CASH                                2000.000000
FINANCED_AMOUNT                          6329.262500
F0089_PROMISE_AMT_1                       170.000000
F0180_CURRENT_INTEREST_RATE                 0.042500
BAL_RAT_TRN_6.1                             0.030000
DPD_bool                                    0.000000
dtype: float64

In [79]:
1.5* IQR["LTVEffective"]+remove_df["LTVEffective"].quantile(0.75)

199408.97177419352

In [82]:
q3=remove_df["LTVEffective"].quantile(0.75)
remove_df.loc[(remove_df["LTVEffective"] > q3+1.5*IQR["LTVEffective"]),"LTVEffective"]= q3+1.5*IQR["LTVEffective"]
remove_df[remove_df["LTVEffective"] > q3+1.5*IQR["LTVEffective"]]["LTVEffective"]

Series([], Name: LTVEffective, dtype: float64)

In [81]:
q3+1.5*IQR["LTVEffective"]

199408.97177419352

In [83]:
for col in remove_df.drop(columns=["PROMISE_STATUS_O","EXTENSION_ELIGIBLE_Y","lastchannel_Z","REM_TM_RAT_OBS","DPD_bool"]).columns:
    remove_df.loc[remove_df[col] > remove_df[col].quantile(0.75)+1.5*IQR[col],col]=remove_df[col].quantile(0.75)+1.5*IQR[col]
    remove_df.loc[remove_df[col] < remove_df[col].quantile(0.25)-1.5*IQR[col],col]=remove_df[col].quantile(0.25)-1.5*IQR[col]
remove_df

,PROMISE_STATUS_O,EXTENSION_ELIGIBLE_Y,F0223_NUMBER_OF_EXTENSIONS,lastchannel_Z,REM_TM_RAT_OBS,ApplicantFICOScore,Appl_Debt,F0066_CONTACT_NO_PROMISE_COUNT,F0315_DAYS_SINCE_LAST_PROMISE_1,F0065_PROMISES_TAKEN_COUNT,...,DepreciationRate,Appl_Income,PTI_BOOKED,SalesTax,DOWN_CASH,FINANCED_AMOUNT,F0089_PROMISE_AMT_1,F0180_CURRENT_INTEREST_RATE,BAL_RAT_TRN_6.1,DPD_bool
0,0.0,0.0,3.0,1.0,0.0,0.0,1075.05,12.0,5.0,25.0,...,0.694261,4138.00,0.0964,708.22,0.0,15057.22,382.68,0.1999,0.01,False
1,0.0,1.0,0.0,1.0,0.0,0.0,1138.75,3.0,45.0,3.0,...,0.776757,4166.67,0.1006,0.00,3500.0,20095.17,419.21,0.1425,0.03,False
2,0.0,1.0,0.0,1.0,0.0,551.0,767.83,0.0,3.0,3.0,...,0.834200,2833.33,0.1525,1916.82,5000.0,18764.82,432.01,0.1808,0.03,False
3,1.0,0.0,2.0,1.0,0.0,468.0,1071.20,14.0,-11.0,10.0,...,0.810160,4000.00,0.0903,0.00,3000.0,15077.00,361.22,0.1970,0.02,False
4,0.0,1.0,0.0,1.0,0.0,523.0,726.64,2.0,80.0,7.0,...,0.810160,2069.02,0.1354,880.60,3000.0,10200.54,280.21,0.2134,0.05,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62933,0.0,0.0,2.0,1.0,0.0,496.0,1808.27,4.0,17.0,7.0,...,0.776757,4991.09,0.0877,1040.82,2000.0,17252.97,437.95,0.1800,0.01,False
62934,1.0,1.0,0.0,1.0,0.0,458.0,720.43,1.0,-16.0,9.0,...,0.856943,2218.75,0.1728,841.68,2100.0,15382.68,402.48,0.2140,0.03,False
62935,0.0,1.0,1.0,1.0,0.0,567.0,852.94,3.0,320.0,13.0,...,0.629297,2810.34,0.1321,872.19,1500.0,15924.07,371.17,0.1650,0.04,False
62936,0.0,0.0,4.0,1.0,0.0,447.0,1026.95,11.0,31.0,16.0,...,0.629297,3704.74,0.1338,1152.30,4000.0,18715.30,500.00,0.2425,0.00,True
62937,0.0,0.0,2.0,1.0,0.0,0.0,860.65,2.0,17.0,1.0,...,0.734352,3500.00,0.0931,0.00,800.0,12305.00,136.03,0.2399,0.03,False

In [86]:
remove_df[remove_df["LTVEffective"] > remove_df["LTVEffective"].quantile(0.75)+1.5*IQR["LTVEffective"]]["LTVEffective"]

Series([], Name: LTVEffective, dtype: float64)

In [88]:
remove_df[remove_df["LTVEffective"] < remove_df["LTVEffective"].quantile(0.25)-1.5*IQR["LTVEffective"]]["LTVEffective"]

Series([], Name: LTVEffective, dtype: float64)

In [89]:
remove_df.to_csv("../ready_to_model_data.csv")
print("saved successfully")

saved successfully